### ISSUE TITLE
add eslint-plugin-unicorn

### ISSUE THREAD

**Issue by targos** [cheminfo/eslint-config#34]
Reviewed so far:

```yml
extends:
  - 'plugin:unicorn/recommended'

rules:
  'unicorn/filename-case': 'off'
  'unicorn/prevent-abbreviations': 'off'
  # TODO: create issue about risk (>32bit integers)
  'unicorn/prefer-math-trunc': 'off'
  'unicorn/prefer-spread': 'off'
  'unicorn/no-new-array': 'off'
  'unicorn/numeric-separators-style': 'off'
  'unicorn/no-for-loop': 'off'
  'unicorn/no-null': 'off'
  'unicorn/switch-case-braces': 'off'
  'unicorn/prefer-ternary': 'off'
  'unicorn/prefer-type-error': 'off'
  'unicorn/no-useless-undefined': 'off'
  # Conflicts with Prettier.
  'unicorn/number-literal-case': 'off'
  # Too early for full ESM
  'unicorn/prefer-module': 'off'
  # Conflicts with Prettier.
  'unicorn/no-nested-ternary': 'off'
  # Problematic with useOnOff
  'unicorn/no-unreadable-array-destructuring': 'off'
  'unicorn/prefer-regexp-test': 'off'
  # Unfortunately too annoying on valid cases + conflicts with TS.
  'unicorn/no-array-callback-reference': 'off'
  # May conflict with other rule + ugly switch(0) auto-fix.
  'unicorn/prefer-switch': 'off'
  # Rare and problematic with APIs that have a find method.
  'unicorn/no-array-method-this-argument': 'off'

  # todo: enable
  # 'unicorn/explicit-length-check': 'warn'
  # 'unicorn/no-array-for-each': 'warn'
  # 'unicorn/no-lonely-if': 'warn'
  # 'unicorn/no-array-push-push': 'warn'
  # 'unicorn/prefer-number-properties': 'warn'
  # 'unicorn/consistent-function-scoping': 'warn'
  # 'unicorn/no-zero-fractions': 'warn'
  # 'unicorn/consistent-destructuring': 'warn'
  # 'unicorn/better-regex': 'warn'
  # 'unicorn/throw-new-error': 'warn'
  # 'unicorn/new-for-builtins': 'warn'
  # 'unicorn/no-instanceof-array': 'warn'
  # 'unicorn/prefer-logical-operator-over-ternary': 'warn'
  # 'unicorn/prefer-native-coercion-functions': 'warn'
  # 'unicorn/prefer-node-protocol': 'warn'
  # 'unicorn/import-style': 'warn'
  # 'unicorn/prefer-export-from': 'warn'
  # 'unicorn/catch-error-name': 'warn'
  # 'unicorn/prefer-optional-catch-binding': 'warn'
  # 'unicorn/prefer-string-slice': 'warn'
  # 'unicorn/prefer-code-point': 'warn'
  # 'unicorn/prefer-query-selector': 'warn'
  # 'unicorn/no-useless-spread': 'warn'
  # 'unicorn/prefer-array-index-of': 'warn'
  # 'unicorn/prefer-set-has': 'warn'
  # 'unicorn/prefer-array-flat-map': 'warn'
  # 'unicorn/no-object-as-default-parameter': 'warn'
  # KEEP as a warning
  # 'unicorn/no-array-reduce': 'warn'
  # 'unicorn/prefer-add-event-listener': 'warn'
  # 'unicorn/prefer-dom-node-append': 'warn'
  # 'unicorn/prefer-dom-node-remove': 'warn'
  # 'unicorn/prefer-array-some': 'warn'
  # 'unicorn/prefer-array-find': 'warn'
  # 'unicorn/prefer-negative-index': 'warn'
  # 'unicorn/prefer-includes': 'warn'
  # 'unicorn/require-array-join-separator': 'warn'
  # 'unicorn/require-number-to-fixed-digits-argument': 'warn'
  # 'unicorn/no-await-expression-member': 'warn'
  # 'unicorn/text-encoding-identifier-case': 'warn'
  # 'unicorn/relative-url-style': 'warn'
  # 'unicorn/no-process-exit': 'warn'
  # 'unicorn/no-useless-promise-resolve-reject': 'warn'
```
